### ISSUE TITLE
Library -> Invfx -> InvFx 윈도우 생성하기 파트 이미지 설명 오류

### ISSUE THREAD

**Issue by Arewena** [HyeonWorks/monun-docs#129]
![image](https://user-images.githubusercontent.com/74582539/233042231-b1d648e7-d409-4cef-bd92-8b0d1e31cd9a.png)

위 사진에서 (5,0)이 아니라 (0,5)로 수정되어야 할거 같습니다.

**Comment by ghost** [comment]
이번주중 수정 PR 달아둘게여
